#!/usr/bin/env python3
"""Reapply native iOS entitlements/Info.plist on every ephemeral Codemagic worker.

Requires the Xcode project generated by `npx cap add ios`. The script intentionally
modifies ONLY the newly generated iOS app and is idempotent.
"""
from pathlib import Path
import plistlib
import subprocess

app = Path('ios/App/App')
info = app / 'Info.plist'
project = Path('ios/App/App.xcodeproj')
if not info.is_file() or not project.is_dir():
    raise SystemExit('Run npx cap add ios (or npx cap sync ios) first.')

with info.open('rb') as f:
    data = plistlib.load(f)
data['NSLocalNetworkUsageDescription'] = (
    'Lúa Design cần kết nối trực tiếp với bộ điều khiển D1 mini để cấu hình Wi-Fi gia đình.'
)
ats = data.setdefault('NSAppTransportSecurity', {})
ats['NSAllowsLocalNetworking'] = True
with info.open('wb') as f:
    plistlib.dump(data, f, sort_keys=False)

entitlements = app / 'App.entitlements'
existing = {}
if entitlements.exists():
    with entitlements.open('rb') as f:
        existing = plistlib.load(f)
existing['com.apple.developer.networking.HotspotConfiguration'] = True
with entitlements.open('wb') as f:
    plistlib.dump(existing, f, sort_keys=False)

# Xcode project files must reference the entitlement for BOTH Debug and Release.
# CocoaPods installs the Ruby xcodeproj gem on Codemagic; no text-based pbxproj hacks.
ruby = r'''
require 'xcodeproj'
p = Xcodeproj::Project.open('ios/App/App.xcodeproj')
target = p.targets.find { |item| item.name == 'App' }
abort 'Xcode app target missing' unless target
target.build_configurations.each do |cfg|
  cfg.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'App/App.entitlements'
end
p.save
'''
subprocess.run(['ruby', '-e', ruby], check=True)
print('iOS: Hotspot Configuration entitlement + Local Network privacy/ATS configured')
